apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
          - name: nginx
            mountPath: /etc/nginx/conf.d
      - image: php:8.2-fpm
        name: php
        volumeMounts:
          - name: html
            mountPath: /var/www/html
      volumes:
        - name: html
          hostPath:
            path: /home/stagiaire/lab-lempnet/html
            type: Directory
        - name: nginx
          hostPath:
            path: /home/stagiaire/lab-lempnet/nginx-conf
            type: Directory
