apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        volumeMounts:
          - name: partage
            mountPath: /usr/share/nginx/html
            subPath: html
          - name: partage
            mountPath: /etc/nginx/conf.d
            subPath: nginx-conf
      - image: php:8.2-fpm
        name: php
        volumeMounts:
          - name: partage
            mountPath: /var/www/html
            subPath: html
      volumes:
        - name: partage
          hostPath:
            path: /home/stagiaire/lab-lempnet
            type: Directory
