apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  annotations:
    lbipam.cilium.io/ips: 192.168.56.90
  labels:
    app: hello
  name: hello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: hello
  type: LoadBalancer
status:
  loadBalancer: {}
