apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: full-access-in-stage-ns
  namespace: stage
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - '*'
