apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: full-access-stage
  namespace: stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-in-stage-ns
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: stage
