apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: list-svc-stage
  namespace: stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-svc
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: stage
