apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        env:
          - name: STAGE
            value: K8S
          - name: JOURS
            value: "5"
          - name: PodIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NameSPC
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FORMATION
            valueFrom:
              configMapKeyRef:
                name: nginx
                key: FORMATION
        envFrom:
          - configMapRef:
              name: nginx
